services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:1.0.2
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - '${PORT_8080:-8080}:8080'
    env_file: .env
    environment:
      - DOCKER_ENABLE_SECURITY
      - INSTALL_BOOK_AND_ADVANCED_HTML_OP
      - LANGS
    volumes:
      - ${VOLUME_DATA}:/usr/share/tessdata
      - ${VOLUME_CONFIG}:/config
