services:
  navidrome:
    image: deluan/navidrome:0.57.0
    container_name: navidrome
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - "${PORT_4533:-4533}:4533"
    env_file: .env
    environment:
      - GID
      - UID
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_ENABLEINSIGHTSCOLLECTOR=false
    volumes:
      - ${VOLUME_DATA}:/data
      - ${VOLUME_MUSIC}:/music:ro
