services:
  myspeed:
    image: germannewsmaker/myspeed:1.0.9
    container_name: MySpeed
    restart: unless-stopped
    ports:
      - ${PORT_5216-5216}:5216
    volumes:
      - ${VOLUME_DATA}:/myspeed/data
