services:
  app:
    image: difegue/lanraragi:v.0.9.40
    container_name: lanraragi
    restart: unless-stopped
    ports:
      - "${PORT_3000:-3000}:3000"
    env_file: .env
    environment:
      - TZ
      - LRR_UID
      - LRR_GID
    volumes:
      - ${VOLUME_CONTENT}:/home/koyomi/lanraragi/content
      - ${VOLUME_DATABASE}:/home/koyomi/lanraragi/database
