services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.7.7
    container_name: adguardhome-sync
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - ${Port_8080:-8080}:8080
    env_file: .env
    environment:
      - TZ
    volumes:
      - ${VOLUME1}:/config/adguardhome-sync.yaml
    command: run --config /config/adguardhome-sync.yaml
