services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - ${VOLUME_SQL}:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.11.2
    container_name: linkwarden
    restart: always
    ports:
      - ${PORT_3000:-3000}:3000
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    volumes:
      - ${VOLUME_DATA}:/data/data
    depends_on:
      - postgres
