services:
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.1.0
    container_name: seerr
    restart: unless-stopped
    ports:
      - ${PORT_5055:-5055}:5055
    env_file: .env
    environment:
      - TZ
      - LOG_LEVEL=debug
    volumes:
      - ${VOLUME_CONFIG}:/app/config
      - /app/node_modules
      - /app/.next