services:
  actual_server:
    image: docker.io/actualbudget/actual-server:25.7.1
    container_name: actualbudget
    restart: unless-stopped
    ports:
      - "${PORT_5006:-5006}:5006"
    volumes:
      - ${VOLUME_DATA}:/data
