services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ${VOLUME_DB_DATA}:/var/lib/postgresql/data

    logging:
      driver: "none"
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wiki
    restart: unless-stopped
    ports:
      - "${Port_3000:-3000}:3000"

    environment:
      - DB_TYPE
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME
    depends_on:
      - db
