services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    ports:
      - "${PORT_8888:-8888}:8888/tcp" #HTTPPROXY        
      - "${PORT_8000:-8000}:8000/tcp" #HTTP_CONTROL_SERVER
      - "${PORT_1080:-1080}:1080" #socks5 proxy
    env_file: .env
    environment:
      - TZ
      - VPN_SERVICE_PROVIDER
      - VPN_TYPE
      - FIREWALL_VPN_INPUT_PORTS
      - WIREGUARD_ADDRESSES
      - WIREGUARD_ENDPOINT_PORT
      - WIREGUARD_PRESHARED_KEY
      - WIREGUARD_PRIVATE_KEY
      - WIREGUARD_PUBLIC_KEY
      - WIREGUARD_ENDPOINT_IP
      - PUBLICIP_API
      - PUBLICIP_API_TOKEN
      - HTTP_CONTROL_SERVER_ADDRESS

    volumes:
      - ${VOLUME_CONFIG_GLUE}:/gluetun/auth/config.toml

    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
  socks5:
    image: serjs/go-socks5-proxy
    container_name: socks5
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
