services:
  vault:
    image: hashicorp/vault:1.20
    container_name: hashivault
    restart: unless-stopped
    user: "0"
    ports:
      - "${PORT_8200:-8200}:8200"
    env_file: .env
    volumes:
      - ${VOLUME_VAULT_DATA}:/vault/data
      - ${VOLUME_VAULT_CONFIG}:/vault/config
    entrypoint: ["/vault/config/entrypoint.sh"]
    cap_add:
      - IPC_LOCK
