services:
  vault:
    image: hashicorp/vault:1.15
    container_name: hashivault
    restart: unless-stopped
    ports:
      - "${PORT_8200:-8200}:8200"
    env_file: .env
    volumes:
      - ${VOLUME_VAULT_DATA}:/vault/data
      - ${VOLUME_VAULT_CONFIG}:/vault/config/vault.hcl
    command: "vault server -config=/vault/config/vault.hcl"
    cap_add:
      - IPC_LOCK
